name: Production deployment

on:
  # We have a new main version
  push:
    branches: [main]
  # the CMS sent a webhook telling us the content has been updated.
  # repository_dispatch:
  #   types: [content_updated]

jobs:
  deploy-static-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions:checkout@v4

      - name: Build static assets
        run: |
          docker build -f ./docker/Dockerfile --target build-prod -t sensatempo-prod:latest .
          docker create --name tmp-container sensatempo-prod:latest
          docker cp tmp-container:/dist ./dist
          docker rm tmp-container

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_PROD_BUCKET }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_DIST_ID }} --paths "/*"
        env:
          - AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          - AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
